services:
  - type: web
    name: kurukshetra-ai-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: CHROMA_PERSIST_DIRECTORY
        value: ./chroma_db
      - key: CHROMA_HOST
        sync: false
      - key: CHROMA_API_KEY
        sync: false
      - key: CHROMA_TENANT
        sync: false
      - key: CHROMA_DATABASE
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "false"
      - key: LANGCHAIN_PROJECT
        value: Kurukshetra_AI
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
