"""add_users_table

Revision ID: 303fa1d461ea
Revises: 4a44b0962f24
Create Date: 2026-06-04 21:12:16.965883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '303fa1d461ea'
down_revision: Union[str, None] = '4a44b0962f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    op.drop_constraint('runs_user_id_fkey', 'runs', type_='foreignkey')
    op.drop_column('runs', 'user_id')
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'password')
    op.add_column('runs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('runs_user_id_fkey', 'runs', 'users', ['user_id'], ['id'])
    op.add_column('projects', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'])
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='refresh_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey')
    )
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    # ### end Alembic commands ###
