"""initial schema

Revision ID: 4a44b0962f24
Revises: 
Create Date: 2026-06-03 20:13:25.642919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a44b0962f24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('version_tag', sa.String(), nullable=False),
    sa.Column('concept', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('iteration_reason', sa.String(), nullable=True),
    sa.Column('agent_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('debate_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('battle_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_version_id'], ['project_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_version_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('idea', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('final_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    op.drop_table('project_versions')
    op.drop_table('projects')
    # ### end Alembic commands ###
